version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: selfio-postgres
    restart: always

    environment:
      POSTGRES_USER: selfio
      POSTGRES_PASSWORD: selfio_pass
      POSTGRES_DB: selfio_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
